//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Swimming_PoolEntities : DbContext
    {
        public Swimming_PoolEntities()
            : base("name=Swimming_PoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessDetails> BusinessDetails { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<Customers_enter> Customers_enter { get; set; }
        public virtual DbSet<open_days> open_days { get; set; }
        public virtual DbSet<otherEnter> otherEnter { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<rentals_details> rentals_details { get; set; }
        public virtual DbSet<Subscribed_customers> Subscribed_customers { get; set; }
        public virtual DbSet<Subscription_type> Subscription_type { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<work_shift_type> work_shift_type { get; set; }
    }
}
